imports:
    - { resource: parameters.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['php']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true



# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:     "%database_driver%"
                host:       "%database_host%"
                port:       "%database_port%"
                dbname:     "%database_name%"
                user:       "%database_user%"
                password:   "%database_password%"
                charset:    UTF8
                mapping_types:
                    enum: string

    orm:
        default_entity_manager:         default
        auto_generate_proxy_classes:    "%kernel.debug%"

        entity_managers:
            default:
                connection:         default
                naming_strategy:    doctrine.orm.naming_strategy.underscore
                mappings:
                    # bundles
                    TagcadeAppBundle:  ~
                    # core entities
                    CoreEntities:
                        type:       yml
                        dir:        %kernel.root_dir%/../src/Tagcade/Resources/config/doctrine/Core
                        prefix:     Tagcade\Entity\Core
                        alias:      TagcadeCoreEntity
                        is_bundle:  false

stof_doctrine_extensions:
    orm:
        default:
            timestampable: true

leezy_pheanstalk:
    pheanstalks:
        primary:
            server: "%pheanstalk_primary_host%"
            default: true