Tagcade\Entity\Core\QueuedFile:
    type: entity
    table: core_imported_file
    repositoryClass: Tagcade\Repository\Core\QueuedFileRepository
    uniqueConstraints:
        queued_file_unique_key:
            columns: # underscore column name
                - hash
                - hash_type
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        filePath:
            type: string
            length: 255
        hash:
            type: string
            length: 255
        hashType:
            type: string
            options:
                default: sha1
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
