#parameters:
#    tagcade.entity.imported_file.class: Tagcade\Entity\Core\ImportedFile

services:
    rest.client:
        class: RestClient\CurlRestClient
        public: false

    tagcade_app.service.tagcade.rest_client:
        class: Tagcade\Service\TagcadeRestClient
        arguments:
            - @rest.client
            - %tagcade_user_name%
            - %tagcade_user_password%
            - %tagcade_get_token_url%
            - %ur_get_data_sources_by_integration_url%
            - %ur_get_data_sources_by_email_url%
            - %ur_receive_file_via_email_webhook_url%
            - %ur_receive_file_via_fetcher_url%



