#parameters:
#    tagcade.entity.imported_file.class: Tagcade\Entity\Core\ImportedFile

services:
    rest.client:
        class: RestClient\CurlRestClient
        public: false

    tagcade.service.redis_cache:
        class: Redis
        calls:
            - [connect, ["%tagcade.redis.host%","%tagcade.redis.port%"]]

    tagcade.service.red_lock:
        class: Tagcade\Service\RedLock
        arguments:
            -
                - '@tagcade.service.redis_cache'
            - '%tagcade.red_lock.retry_delay%'
            - '%tagcade.red_lock.retry_count%'

    tagcade.service.retry_cycle_service:
        class: Tagcade\Service\RetryCycleService
        arguments:
            - '@tagcade.service.redis_cache'
            - '%tagcade.retry_cycle_prefix_key%'
            - '%tagcade.max_retry_key_expire_time%'

    tagcade_app.service.tagcade.rest_client:
        class: Tagcade\Service\TagcadeRestClient
        arguments:
            - '@rest.client'
            - '%tagcade_user_name%'
            - '%tagcade_user_password%'
            - '%tagcade_get_token_url%'
            - '%ur_get_data_sources_by_integration_url%'
            - '%ur_get_data_sources_by_email_url%'
            - '%ur_receive_file_url%'



